"""add discounts

Revision ID: 05e32c465124
Revises: 3d9da8842c82
Create Date: 2024-08-12 14:49:13.094261

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05e32c465124'
down_revision = '3d9da8842c82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
                    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('open_type',
                              sa.Enum('web_view', 'browser', 'browser_tab', 'deeplink', name='discountopentype'),
                              nullable=False),
                    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discount')
    # ### end Alembic commands ###
