"""add product translations

Revision ID: 0ec3e55d6b1e
Revises: 376c21dcd34c
Create Date: 2024-08-14 21:21:05.966107

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ec3e55d6b1e'
down_revision = '376c21dcd34c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_translation',
                    sa.Column('language_code', postgresql.ENUM('en', 'uk', name='languagecode',create_type=False), nullable=False),
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('language_code', 'id')
                    )
    op.drop_column('product', 'name')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('product_translation')
    # ### end Alembic commands ###
