"""add marks

Revision ID: 2358bf4063bf
Revises: d98cb24235a7
Create Date: 2024-08-13 17:10:27.681411

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '2358bf4063bf'
down_revision = 'd98cb24235a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark',
                    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=False),
                    sa.Column('longitude', sa.Float(), nullable=False),
                    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('mark_working_hours',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('mark_id', sa.Uuid(), nullable=False),
                    sa.Column('day',
                              sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
                                      name='day'), nullable=False),
                    sa.Column('open_at', sa.Time(), nullable=False),
                    sa.Column('close_at', sa.Time(), nullable=False),
                    sa.Column('work_type', sa.Enum('default', 'delivery', name='worktype'), nullable=False),
                    sa.ForeignKeyConstraint(['mark_id'], ['mark.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mark_working_hours')
    op.drop_table('mark')
    # ### end Alembic commands ###
