"""add category translations

Revision ID: 376c21dcd34c
Revises: 2358bf4063bf
Create Date: 2024-08-14 19:50:22.488979

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '376c21dcd34c'
down_revision = '2358bf4063bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_translation',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('language_code', sa.Enum('en', 'uk', name='languagecode'), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['category.id'], ),
                    sa.PrimaryKeyConstraint('id', 'language_code')
                    )
    op.drop_column('category', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('category_translation')
    # ### end Alembic commands ###
