"""add product model

Revision ID: 3d9da8842c82
Revises: 7666841a95e0
Create Date: 2024-08-06 13:50:57.132062

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d9da8842c82'
down_revision = '7666841a95e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('image_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product',
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('unit', sa.Enum('piece', 'gram', name='unit'), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('calories', sa.Float(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product_ingredient_link',
                    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
                    sa.Column('product_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('ingredient_id', 'product_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_ingredient_link')
    op.drop_table('product')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
