"""update image variables

Revision ID: d98cb24235a7
Revises: 05e32c465124
Create Date: 2024-08-12 18:39:12.963589

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd98cb24235a7'
down_revision = '05e32c465124'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('discount', 'image_path')
    op.add_column('ingredient', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('ingredient', 'image_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('image_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ingredient', 'image_url')
    op.add_column('discount', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('discount', 'image_url')
    # ### end Alembic commands ###
